# Generated by Django 2.2.6 on 2020-02-14 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0003_marca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name_plural': 'Marcas'},
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('usuarioModifica', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción de la unidad de medida', max_length=100, unique=True)),
                ('usuarioCrea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Unidades de medida',
            },
        ),
    ]
