# Generated by Django 2.2.6 on 2020-02-14 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('codigo', 'codigoBarra')},
        ),
    ]
