# Generated by Django 2.2.6 on 2020-02-25 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_detallefactura_factura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallefactura',
            old_name='descuento',
            new_name='descuentoDetalle',
        ),
    ]
