# Generated by Django 2.2.6 on 2020-02-25 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_auto_20200224_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallefactura',
            old_name='total',
            new_name='totalDetalle',
        ),
    ]
