# Generated by Django 2.2.6 on 2020-02-25 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_auto_20200224_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallefactura',
            old_name='subTotal',
            new_name='subTotalDescuento',
        ),
    ]
