# Generated by Django 2.2.6 on 2020-02-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_auto_20200224_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallefactura',
            old_name='subTotalDescuento',
            new_name='subTotalDetalle',
        ),
    ]
