# Generated by Django 2.2.6 on 2020-02-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_auto_20200226_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallefactura',
            options={'permissions': [('sup_caja_detalleFactura', 'Permisos de supervisor de caja Detalle Factura')], 'verbose_name': 'Detalle factura', 'verbose_name_plural': 'Detalle facturas'},
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'permissions': [('sup_caja_factura', 'Permisos de supervisor de caja Factura')], 'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
    ]
